export const SET_INIT = 'SET_INIT';
export const SET_TOKEN = 'SET_TOKEN';
export const REMOVE_TOKEN = 'REMOVE_TOKEN';
export const SAVE_TOKEN = 'SAVE_TOKEN';
export const SET_ENTERPRISE = 'SET_ENTERPRISE';
export const CREATE_ENTERPRISE = 'CREATE_ENTERPRISE';
export const EDIT_ENTERPRISE = 'EDIT_ENTERPRISE';
export const REMOVE_ENTERPRISE = 'REMOVE_ENTERPRISE';